/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.brightvending;

/**
 *
 * @author User
 */
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.*;
import javax.swing.JOptionPane;
        
public class adminManageProductForm extends javax.swing.JFrame {
    private final String productfile = "src/main/java/com/mycompany/brightvending/files/product.txt";
    private String action;
    private String imagePath;
    
    public void setMode(String modeAction){
        this.action = modeAction;
    }
  
    /**
     * Creates new form adminManageProductForm
     */
    
    public adminManageProductForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        picturePanel = new javax.swing.JPanel();
        PictureLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        productStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fileChoserBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        DoneBtn = new javax.swing.JButton();
        priceInvalidLabel = new javax.swing.JLabel();
        stockInvalidLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Product Information ");
        setIconImage(Toolkit.getDefaultToolkit().getImage("src\\main\\java\\com\\mycompany\\brightvending\\image\\icon-vending-machine-64.png"));
        setMinimumSize(new java.awt.Dimension(641, 671));
        setResizable(false);
        setSize(new java.awt.Dimension(641, 671));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(641, 671));
        jPanel1.setMinimumSize(new java.awt.Dimension(641, 671));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Product Information Management");
        jLabel1.setToolTipText("");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        picturePanel.setBackground(new java.awt.Color(204, 255, 255));
        picturePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout picturePanelLayout = new javax.swing.GroupLayout(picturePanel);
        picturePanel.setLayout(picturePanelLayout);
        picturePanelLayout.setHorizontalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, picturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );
        picturePanelLayout.setVerticalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Product Name");

        productName.setBackground(new java.awt.Color(204, 255, 255));
        productName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        productName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Product Price");

        productPrice.setBackground(new java.awt.Color(204, 255, 255));
        productPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        productPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPriceActionPerformed(evt);
            }
        });
        productPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productPriceKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Number of stock");

        productStock.setBackground(new java.awt.Color(204, 255, 255));
        productStock.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        productStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productStockActionPerformed(evt);
            }
        });
        productStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productStockKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Product Picture");

        fileChoserBtn.setBackground(new java.awt.Color(204, 255, 204));
        fileChoserBtn.setForeground(new java.awt.Color(0, 0, 0));
        fileChoserBtn.setText("Choose picture");
        fileChoserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChoserBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(255, 153, 153));
        cancelBtn.setForeground(new java.awt.Color(0, 0, 0));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        DoneBtn.setBackground(new java.awt.Color(255, 255, 153));
        DoneBtn.setForeground(new java.awt.Color(0, 0, 0));
        DoneBtn.setText("Done");
        DoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneBtnActionPerformed(evt);
            }
        });

        priceInvalidLabel.setForeground(new java.awt.Color(255, 102, 102));

        stockInvalidLabel.setForeground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(DoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(picturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(productPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productStock, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(fileChoserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceInvalidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockInvalidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(picturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceInvalidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productStock, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(stockInvalidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileChoserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productPriceKeyReleased
        // TODO add your handling code here:
        String pattern = "\\d{1,9}\\.\\d+";
        Pattern p = Pattern.compile(pattern);
        Matcher match = p.matcher(productPrice.getText());
        if (!match.matches()) {
            priceInvalidLabel.setText("Invalid");
        }
        else {
            priceInvalidLabel.setText("");
        }
    }//GEN-LAST:event_productPriceKeyReleased

    private void productPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPriceActionPerformed

    private void productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameActionPerformed

    private void DoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneBtnActionPerformed

        int product_id ;
        String product_name, p_price, product_price, product_stock, picture_path, modeForInsert = "";
        double temp;

        product_name = productName.getText();
        p_price = productPrice.getText();
        product_stock = productStock.getText();
        picture_path = imagePath;
        
        // 1) VALIDATE INPUT
        // validate empty
        if (product_name.isEmpty() || p_price.isEmpty() || product_stock.isEmpty() || picture_path.isEmpty() || picture_path == null) {
            JOptionPane.showMessageDialog(null,"Please make sure every input is filled with valid input.","Alert",JOptionPane.WARNING_MESSAGE);
            return;
        }
        // validate if the input is in the correct form or not (if not the labels will have text)
        if (!"".equals(priceInvalidLabel.getText()) || !"".equals(stockInvalidLabel.getText())) {
            JOptionPane.showMessageDialog(null,"Please make sure every input is filled with valid input.","Alert",JOptionPane.WARNING_MESSAGE);
            return;
        }
        temp = Double.parseDouble(p_price);
        product_price = dformat.format(temp);

        // 2) GENERATE ID
        product_id = CRUDFileHandling.IDgeneration(productfile);

        // 3) EITHER INSERT/ UPDATE RECORD
        String[] recordContent = {product_id + ";" + product_name + ";" + product_price +";" + product_stock+ ";" + picture_path};
        String header = "ProductID;ProductName;ProductPrice;Stock;ProductPicture";

        if (null != action) switch (action) {
            case "add":
                modeForInsert="append";
                break;
            case "edit":
                modeForInsert="overwrite";
                break;
            case "":
                JOptionPane.showMessageDialog(null,"action did not specified.","Alert",JOptionPane.WARNING_MESSAGE);
                return;
            default:
                break;
        }
        
        Object[] insert_record_msg = CRUDFileHandling.InsertRecord(productfile, recordContent, header, modeForInsert);
        String msgTitle = (String) insert_record_msg[0];
        String msgContent = (String) insert_record_msg[1];
        if (msgTitle != "ERROR") {
            JOptionPane.showMessageDialog(null, msgContent, msgTitle, JOptionPane.INFORMATION_MESSAGE);
            productName.setText("");
            productPrice.setText("");
            productStock.setText("");
            PictureLabel.setIcon(new ImageIcon(""));
        }
        else{
            JOptionPane.showMessageDialog(null, msgContent, msgTitle, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_DoneBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void fileChoserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChoserBtnActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser browseImageFile = new JFileChooser();

            // Filter image extensions
            browseImageFile.addChoosableFileFilter(new filterImg());
            browseImageFile.setAcceptAllFileFilterUsed(false);
            browseImageFile.showOpenDialog(null);
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();

            // Display image on jLable
            ImageIcon image = new ImageIcon(selectedImagePath);
            // Resize image to fit jLabel
            Image img = image.getImage().getScaledInstance(PictureLabel.getWidth(), PictureLabel.getHeight(), Image.SCALE_SMOOTH);
            PictureLabel.setIcon(new ImageIcon(img));

            // move to new path
            String newPath = "src/main/java/com/mycompany/brightvending/image/productImage/";
            imagePath = newPath;
            File directory = new File(imagePath);
            if(!directory.exists()) {
                directory.mkdirs();
            }

            File sourceFile = null;
            File destinationFile = null;
            String extension = selectedImagePath.substring(selectedImagePath.lastIndexOf(".")+1);
            sourceFile = new File(selectedImagePath);
            int uniqueID = CRUDFileHandling.IDgeneration(productfile);
            imagePath = newPath+uniqueID+"newImage." + extension;
            Path path = Paths.get(imagePath);
            if ( Files.exists(path)) {
                File tobeDelete = new File(imagePath);
                tobeDelete.delete();
            }

            destinationFile =  new File (imagePath);
            Files.copy(sourceFile.toPath(), destinationFile.toPath());
            
        } catch (IOException ex) {
            Logger.getLogger(adminManageProductForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fileChoserBtnActionPerformed

    private void productStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productStockActionPerformed

    private void productStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productStockKeyReleased
        // TODO add your handling code here:
        String pattern = "\\d{1,9}";
        Pattern p = Pattern.compile(pattern);
        Matcher match = p.matcher(productStock.getText());
        if (!match.matches()) {
            stockInvalidLabel.setText("Invalid");
        }
        else {
            stockInvalidLabel.setText("");
        }
    }//GEN-LAST:event_productStockKeyReleased

    private static final DecimalFormat dformat = new DecimalFormat("0.00");

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminManageProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminManageProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminManageProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminManageProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                adminManageProductForm form =new adminManageProductForm();
                /*
                form.productName.setText(p_name);
                String pPrice =""+p_price;
                form.productPrice.setText(pPrice);
                String pStock = "" + p_stock;
                form.productStock.setText(pStock);
                form.PictureLabel.setIcon(new ImageIcon(pictureDir));
                */
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoneBtn;
    private javax.swing.JLabel PictureLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton fileChoserBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel picturePanel;
    private javax.swing.JLabel priceInvalidLabel;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productPrice;
    private javax.swing.JTextField productStock;
    private javax.swing.JLabel stockInvalidLabel;
    // End of variables declaration//GEN-END:variables
}
