/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.brightvending;

/**
 *
 * @author User
 */

import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.TimerTask;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


public class UI_vending_admin extends javax.swing.JFrame {
    /**
     * Creates new form UI_vending_admin
     */
    public UI_vending_admin() {
        initComponents();
        setTitle("Bright Vending Machine | Admin Product Management");
        importDataToTable();
      ProductTable.setRowHeight(ProductTable.getRowHeight() + 20);
         Timer time = new Timer();
        time.schedule(new TimerTask() {
          @Override
          public void run() {
//            constantRefresh();
                LocalDateTime dateTimeNow = LocalDateTime.now();
                DateTimeFormatter dateTimeFormator = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
                String formattedDateTime = dateTimeFormator.format(dateTimeNow);
                Timer1.setText(formattedDateTime);
          }
        }, 0, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Exit1 = new javax.swing.JButton();
        Timer1 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        salesReportBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage("src\\main\\java\\com\\mycompany\\brightvending\\image\\icon-vending-machine-64.png"));
        setMinimumSize(new java.awt.Dimension(1024, 786));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 786));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 786));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 786));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 78, 156));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bright Vending Machine");

        Exit1.setText("Exit");
        Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit1ActionPerformed(evt);
            }
        });

        Timer1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        Timer1.setText("Timer");
        Timer1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        saveBtn.setBackground(new java.awt.Color(51, 102, 255));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save changes");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(51, 102, 255));
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add New Product");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        salesReportBtn.setBackground(new java.awt.Color(255, 102, 102));
        salesReportBtn.setForeground(new java.awt.Color(0, 0, 0));
        salesReportBtn.setText("Sales Report");
        salesReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesReportBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Prodct Price", "Stock", "Product Picture"
            }
        ));
        ProductTable.setToolTipText("");
        ProductTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(ProductTable);

        deleteBtn.setBackground(new java.awt.Color(51, 102, 255));
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete Selected Product");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        refreshBtn.setBackground(new java.awt.Color(204, 255, 204));
        refreshBtn.setForeground(new java.awt.Color(0, 0, 0));
        refreshBtn.setText("REFRESH TABLE");
        refreshBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Product management");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("          Report");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Timer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(Exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveBtn,javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(salesReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Exit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Timer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salesReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(56, 56, 56))
            );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salesReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesReportBtnActionPerformed
        // TODO add your handling code here:
        admin_sales_report reportpage = new admin_sales_report();
        reportpage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        reportpage.pack();
        reportpage.setResizable(false);
        reportpage.setLocationRelativeTo(null);
        reportpage.setVisible(true);
    }//GEN-LAST:event_salesReportBtnActionPerformed

    private void Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        customer_login page = new customer_login();
         page.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        page.pack();
        page.setResizable(false);
        page.setLocationRelativeTo(null);
        page.setVisible(true);
    }//GEN-LAST:event_Exit1ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        int res = JOptionPane.showConfirmDialog(null, "**PLEASE MAKE SURE YOU HAVE HIT [ENTER] ON KEY BOARD AFTER U EDIT THE TABLE RECORD**\nAre you sure you wanted to save the change you have made in the table?\n\nNote: The changes made on table will NOT be validate, it might CRASH the system if invalid data is entered.\nPlease make sure every data is valid before you save.");
        if (res == JOptionPane.YES_OPTION) {
            String productFile = "src/main/java/com/mycompany/brightvending/files/product.txt";
            String header = "ProductID;ProductName;ProductPrice;Stock;ProductPicture";
            int numberOfRow = ProductTable.getRowCount();
            int numberOfCol = ProductTable.getColumnCount();
            try {
                FileWriter fwriter = new FileWriter(productFile, false);
                BufferedWriter bwriter= new BufferedWriter(fwriter);
                bwriter.write(header+"\n");
                for (int i=0; i<numberOfRow; i++) {
                    for (int j=0; j<numberOfCol;j++) {
                        if(j == numberOfCol-1) {
                            String dataRecord= ProductTable.getModel().getValueAt(i,j).toString();
                            bwriter.write(dataRecord);
                        } 
                        else {
                        // convert data into string
                        String dataRecord= ProductTable.getModel().getValueAt(i,j).toString()+ ";";
                        bwriter.write(dataRecord);     
                    }
                    }
                    bwriter.newLine();
                }
                bwriter.close();
                fwriter.close();
            }
            catch (IOException ex) {
                Logger.getLogger(UI_vending_admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        adminManageProductForm addProductForm = new adminManageProductForm();
        addProductForm.setMode("add");
        addProductForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addProductForm.pack();
        addProductForm.setResizable(false);
        addProductForm.setLocationRelativeTo(null);
        addProductForm.setVisible(true);
    }//GEN-LAST:event_addBtnActionPerformed

    
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int i = ProductTable.getSelectedRow();
        if (i >=0) {
            int res = JOptionPane.showConfirmDialog(null, "Are you sure you wanted to delete the selected product?");
            if (res == JOptionPane.YES_OPTION) {
//                delete the record
                DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
                String productID = (String) model.getValueAt(i, 0);
                String path = "src/main/java/com/mycompany/brightvending/files/product.txt";
                Object[] msgReturned = CRUDFileHandling.FetchOneRecord(path, productID);
                for (Object record : msgReturned) {
                    if (record == "ERROR") {
                        JOptionPane.showMessageDialog(null, record);
                        return;
                    }
                }
                Object[] deleteMessage = CRUDFileHandling.DeleteRecord(path, msgReturned);
                if (deleteMessage[0] == "ERROR") {
                    JOptionPane.showMessageDialog(null, deleteMessage[1].toString(), deleteMessage[0].toString() , JOptionPane.WARNING_MESSAGE);
                    return;
                }
//                model.removeRow(i);    
                JOptionPane.showMessageDialog(null, "deleted successfully");

            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a record from the table first.");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        model.setRowCount(0);
        importDataToTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    public void constantRefresh() {
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        model.setRowCount(0);
        importDataToTable();
    }
    
    private void importDataToTable() {
            String filePath= "src/main/java/com/mycompany/brightvending/files/product.txt";
            Object[] fetchedProduct = CRUDFileHandling.FetchRecord(filePath);
            if (fetchedProduct.length == 0) {
                return;
            }
            if (fetchedProduct[0] == "ERROR") {
                 JOptionPane.showMessageDialog(null, fetchedProduct[1],"Alert",JOptionPane.WARNING_MESSAGE);
            }
            else {
                DefaultTableModel model = (DefaultTableModel)ProductTable.getModel();
                for (int i = 0; i < fetchedProduct.length; i++) {
                    if (i == 0) {
                        continue;
                    }
                    String record = (String) fetchedProduct[i];
                    String[] data = record.split(";");
                    model.addRow(data);
                }
            }
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_vending_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_vending_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_vending_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_vending_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UI_vending_admin mainpage = new UI_vending_admin();
                mainpage.setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton Exit1;
    private javax.swing.JTable ProductTable;
    private javax.swing.JLabel Timer1;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton salesReportBtn;
    // End of variables declaration//GEN-END:variables
}
